server:
  port: 8761

spring:
  application:
    name: ead-service-registry

ead:
  serviceRegistry:
    username: serviceRegistry
    password: ${SERVICE_REGISTRY_PASSWORD}

eureka:
  client:
    register-with-eureka: false # Nao registrar ele mesmo, pra nao ser o client
    fetch-registry: false # Nao buscar um registro no eureka
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'