server:
  port: 8761

spring:
  application:
    name: ead-service-registry

eureka:
  client:
    register-with-eureka: false # Nao registrar ele mesmo, pra nao ser o client
    fetch-registry: false # Nao buscar um registro no eureka